version: "3.9"

services:
  web:
    build: .
    container_name: smart-farm-app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: smart-farm-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: agriculture_portal
      MYSQL_USER: aguser
      MYSQL_PASSWORD: Bipinsingh1
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password